### ISSUE TITLE
unable to use discovery type azure

### ISSUE THREAD

**Issue by aeroinfoes** [elastic/elasticsearch-cloud-azure#121]
hi,
we have installed cloud-azure plugin but are not able to get it working on ES version 2.3.5. The plugin is being loaded, but the error we get is the following:
```
java.lang.IllegalArgumentException: Unknown Discovery type [azure]
        at org.elasticsearch.discovery.DiscoveryModule.configure(DiscoveryModule.java:100)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Our YML config looks like this:

```
cloud:
  azure:
      subscription.id: <our sub id>
      service.name: <our rg name>
      keystore: /usr/tmp/certificate.pfx
      password: <our pass>

discovery:
  type: azure
```
for "service.name": we have used our resource group name, as we do not create any VMs under cloud service. Our existing architecture is simply not set up that way. Is this a problem?

We did find some conflicting information on the config, so if someone could help us with which is correct that would be great:

1. Some sources specify that your YML should be configured as "subscription.id" others as "subscripton_id". Which is correct? (ex this person who was able to get it working uses "_" https://gist.github.com/dendle/0a816f28fd0bfdfced44)

2. is it correct to use:
 `discovery.type: azure` 
or 
```
`discovery: 
      zen.hosts_provider: azure`
```
We dont know which is appropriate. Here is an example of zen.hosts_provider being used: https://www.elastic.co/guide/en/elasticsearch/plugins/master/discovery-azure-classic-usage.html)

3. Is there a restriction on what can be used for "keystore"? Must it be a .pkcs12 or can a .pfx be used?

Thank you

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.

This repository is now closed as everything moved to https://github.com/elastic/elasticsearch now.

This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
