### ISSUE TITLE
ES 1.7.0 Plugin 2.8.0 "NullPointerException[null]",    "status": 500 while getting list of snapshots.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-cloud-azure#98]
I was able to create my snapshot
```
GET _snapshot/ex_organizations/_status
PUT _snapshot/ex_organizations
{
  "type": "azure",
    "settings": {
       "base_path": "organizations"
    }
}
```
and call status.

But when I call `GET _snapshot/ex_organizations/_all` I get the following error:

```json
{
   "error": "NullPointerException[null]",
   "status": 500
}
```

I'm trying to restore from a backup in blob storage. The cluster names are diff (`a` vs `a-dev`)

**Comment by imotov** [comment]
Is there an exception in the log file that corresponds to the error?

**Comment by niemyjski** [comment]
Nub question, but which log file should I be checking :)?

**Comment by imotov** [comment]
The log file that I am interested in is located in the `logs` directory and is called the same way as your cluster with .log extension. So, by default the file is `elasticsearch.log`. The location of the `logs` directory is a bit trickier question. It depends on how you installed elasticsearch. Please find your package in https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-dir-layout.html and see where this directory is located. Thanks!

**Comment by niemyjski** [comment]
I found this in my log file:

```
[2015-07-20 16:38:15,380][WARN ][snapshots                ] [ex-xxxx-es01] [ex_organizations][2015-07-20-15-30] failed to restore snapshot
java.lang.NullPointerException
        at org.elasticsearch.cloud.azure.storage.AzureStorageServiceImpl.getInputStream(AzureStorageServiceImpl.java:164)
        at org.elasticsearch.cloud.azure.blobstore.AzureBlobContainer.openInput(AzureBlobContainer.java:74)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.readSnapshot(BlobStoreRepository.java:411)
        at org.elasticsearch.snapshots.RestoreService.restoreSnapshot(RestoreService.java:153)
        at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:86)
        at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:41)
        at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3.run(TransportMasterNodeOperationAction.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dadoonet** [comment]
It sounds like `base_path` is actually not implemented. It's only implemented in mock for tests :(

Can you try without `base_path`?

**Comment by dadoonet** [comment]
See also https://github.com/elastic/elasticsearch/issues/13773

**Comment by niemyjski** [comment]
I tried without a base path and same thing. I just upgraded everything to 1.7.2 and 1.8.1 respectively and still seeing the same thing. I'd be more than happy to do a remote meeting with you if you wanted to take a look.

**Comment by niemyjski** [comment]
I think I just narrowed this down. I was using a secondary access key and I updated my config to use the primary key and it started working (so far)

**Comment by dadoonet** [comment]
Ah cool to know! So we can for now close this issue?

**Comment by niemyjski** [comment]
Well I think the behavior is unacceptable. I think that if the storage key doesn't work the message should tell you instead of a null ref with no context

Sent from Outlook




On Tue, Sep 29, 2015 at 9:52 AM -0700, "David Pilato" <notifications@github.com> wrote:












Ah cool to know! So we can for now close this issue?

**Comment by dadoonet** [comment]
Can we relabel then the issue?
Can you provide also an example of a bad `elasticsearch.yml` that is throwing this NPE so we can write a test and fix that?
